# Generated by Django 4.1 on 2022-10-07 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0003_perfilusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilUsuario',
            new_name='UserProfile',
        ),
    ]
